### PR TITLE
Add shebang to make nuimo.py executable

### PR DESCRIPTION
**Pull request by shaftoe**
You could ignore the README change, but I think having that first line in the script makes it more flexible/portable

### CODE REVIEW

**Comment by larsblumberg** [comment]
While I see the usefulness of your pull request (it saves you from typing `python ...`) it does blow up the documentation. The documentation aims to be as compact as possible to give everybody with a Raspberry Pi a starting point to use Nuimo. Having that extra step to change execution permission doesn't serve the purpose of presenting a minimal manual about how to communicate with Nuimo. I appreciate your pull request but for the aforementioned reasons I won't merge it.

**Comment by shaftoe** [comment]
Sure, I understand about the docs, I still think though is a good idea to have the shebang as first line, it won't limit it to be invoked as `python nuimo.py` as in the current docs and at the same time it will make it a normal executable script for whoever prefer to use it as such

**Comment by larsblumberg** [comment]
Good point! I'll add the shebang line from your suggestion. Thank you!

**Comment by larsblumberg** [comment]
d7c7701af3bd92de64fc4658b42bc96914164b9c

**Pull request closed without merging**
